name: map_route
description: "A Flutter package for visual routing. for testing purposes only."
version: 1.0.3

homepage: https://github.com/AlexHCJP/map_route
repository: https://github.com/AlexHCJP/map_route
issue_tracker: https://github.com/AlexHCJP/map_route/issues

topics: 
  - flutter
  - routing
  - graph-view
  - visualization
  - ui-testing

platoform:
  android: true
  ios: true
  web: true
  linux: true
  macos: true
  windows: true

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  graphify: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
